"""Adiciona campo imagem ao Produto

Revision ID: 744fd54da892
Revises: 2654c90f9483
Create Date: 2025-07-03 14:20:43.830054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744fd54da892'
down_revision = '2654c90f9483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_column('imagem')

    # ### end Alembic commands ###
